""" 
Problem Statement: Count and Say

The "Count and Say" sequence is a sequence of strings that starts with "1" and each subsequent string is generated by 
reading the previous string aloud and counting the occurrences of each digit. The next string is then constructed by stating the count of each 
digit consecutively, followed by the digit itself. 

For example:
- The sequence starts with "1".
- The second string is generated by "counting and saying" the digits of the first string, which is "one 1", so the second string becomes "11".
- The third string is generated by "counting and saying" the digits of the second string, which is "two 1s", so the third string becomes "21".
- The fourth string is generated by "counting and saying" the digits of the third string, which is "one 2, one 1", so the fourth string becomes "1211".
- And so on...

You are given an integer n, your task is to generate the nth string in the "Count and Say" sequence.

Input:
- An integer n (1 ≤ n ≤ 30)

Output:
- The nth string in the "Count and Say" sequence.

Example:
Input: n = 4
Output: "1211"
Explanation: The fourth string in the sequence is "one 2, one 1", which is "1211".

"""

# Driver Code
num = 3322251
num_str = str(num)

def str_to_text(num):
    num = num.replace("1","One ")
    num = num.replace("2","Two ")
    num = num.replace("3","Three ")
    num = num.replace("4","Four ")
    num = num.replace("5","Five ")
    num = num.replace("6","Six ")
    num = num.replace("7","Seven ")
    num = num.replace("8","Eight ")
    num = num.replace("9","Nine ")
    num = num.replace("0","Zero ")
    return num

num_str = str_to_text(num_str)
print(num_str)

def count(num):



# My Learnings 

# 1. Replace Function don't change the original string it simply shows the modified string 
# 2. Strings in Python are Immutable
# 3.